emqx/emqx-rel

.gitignore
Makefile
bin/emqttd
ct/emqtt.spec
ct/run_emqtt.sh
relx.config

https://github.com/emqtt/emqttd/issues/842

Add ct/emqtt.spec and Fix emqttd issue#842

---

bin/emqx

rename EMQ_NODE_NAME to EMQX_NODE_NAME
rename EMQ_NODE_COOKIE to EMQX_NODE_COOKIE。

rename EMQ_* to EMQX_*

---

.ci/files/emqx_nightly_ci.sh
.ci/files/emqx_release_ci.sh
.ci/mac_ci.sh

Update release and nightly build script

Update release and nightly build script

---

Makefile

https://github.com/emqx/emqx/pull/2057

Rename vm.args.cloud -> vm.args

---

tests/run_emqx.sh

Emqx30 zhanght2

---

relx.config

Revert "Create 'data/scripts' folder for lua-hook scripts"

---

Makefile

Prior to this change, the typo of dependencies in Makefile is messed and not clear. I put these dependencies in order to make it more clear.

Put dependencies in order

---

.gitignore
data/loaded_plugins
data/loaded_plugins.tmpl
post-compile.sh
rebar.config
rebar.config.script
vars-cloud.config
vars-edge.config

This is the very first step deprecating erlang.mk
Not changing dependency versioning and locking issues in this PR,
not that it's not important, but simply because it is a whole different issue
which can be and should be addressed separately.
Marked as WIP because some dependencies have PR to merge.

[WIP] Make possible to build release with rebar3

---

README.md

Fix the error of commands guide for https://github.com/emqx/emqx-rel/issues/335

Fix README commands error

---

Makefile
rebar.config
rebar.config.script

There are still some problems to resolve

Better build

---

deploy/packages/Makefile

Modify the determination of centos system

 Modify the determination of centos system

---

deploy/packages/deb/debian/postinst

Fix issue: https://github.com/emqx/emqx/issues/2890

Fix apt upgrade error

---

rebar.config.script

Improve rebar script

---

deploy/docker/Dockerfile
deploy/docker/Makefile
deploy/packages/Makefile

+ Upgrade erlang version to 22.1 for docker
+ Upgrade alpine to 3.10 for docker
+ Change the default version number to 4.0

Change erlang version for docker

---

deploy/docker/docker-entrypoint.sh

Fix https://github.com/emqx/emqx-rel/issues/442

Fix error for #442

---

deploy/charts/emqx/templates/configmap.yaml

Thanks for [xTheRamon](https://github.com/xTheRamon)'s contribution. This PR is used instead of [PR#449](https://github.com/emqx/emqx-rel/pull/449).

Update configmap.yaml to fix ReadString error

---

deploy/charts/emqx/README.md
deploy/charts/emqx/templates/StatefulSet.yaml
deploy/charts/emqx/templates/configmap_for_acl.yaml
deploy/charts/emqx/values.yaml

Acl.conf can be configured separately in helm chart

Acl.conf can be configured separately

---

deploy/packages/rpm/Makefile

Signed-off-by: Guoyun Sun <sunguoyun@loongson.cn>

FIXBUG:make emqx-pkg cannot support other architecture

---

.github/workflows/build_packages.yaml
deploy/docker/docker-entrypoint.sh

A defined environment variable with an empty value is interpreted as a deleted config entry. Just like this command: https://github.com/emqx/emqx-rel/issues/434#issuecomment-606170706

Update docker entrypoint

---

deploy/docker/README.md

Done https://github.com/emqx/emqx/issues/3427

docs: Better documentation for EMQX Docker usage

---

deploy/docker/README.md

Revert "docs: Better documentation for EMQX Docker usage"

---

deploy/docker/docker-entrypoint.sh

prevent sensitive env from leaking to console

---

bin/emqx
deploy/docker/README.md
deploy/docker/docker-entrypoint.sh

Done https://github.com/emqx/emqx-rel/issues/535#event-3475382154

feature(docker): load modules on docker

---

deploy/charts/emqx/templates/service.yaml

same as  https://github.com/emqx/emqx-rel/pull/534

chore(helm): add helm chart service annotations (#534)

---

deploy/docker/docker-entrypoint.sh

same as https://github.com/emqx/emqx-rel/pull/525

feat(docker): prevent sensitive env from leaking to console (#525)

---

bin/emqx
deploy/docker/README.md
deploy/docker/docker-entrypoint.sh

same as https://github.com/emqx/emqx-rel/pull/540

feature(docker): load modules on docker (#540)

---

deploy/docker/docker-entrypoint.sh

Hot fix https://github.com/emqx/emqx-rel/issues/535#issuecomment-653668643

fix(docker): fix wrong format of load_plugins when docker start

---

deploy/docker/README.md
deploy/docker/docker-entrypoint.sh

`MASK_CONFIG_FILTER` to configure setting to mask sensitive config

---

bin/emqx
deploy/docker/Dockerfile
deploy/docker/start.sh

chore(docker): print erlang.log

---

bin/emqx
deploy/docker/Dockerfile
deploy/docker/README.md
deploy/docker/docker-entrypoint.sh
deploy/docker/start.sh

+ Fix #524
+ Fix https://github.com/emqx/emqx-rel/issues/552 https://github.com/emqx/emqx/issues/3559
+ Fix https://github.com/emqx/emqx-rel/pull/546#discussion_r458803576

fix(docker): print docker log

---

deploy/docker/docker-entrypoint.sh

Fix https://github.com/emqx/emqx-rel/pull/546#discussion_r458803576

fix: fix error for docker

---

deploy/charts/emqx/README.md
deploy/charts/emqx/templates/ingress.yaml
deploy/charts/emqx/values.yaml

Enable ingress for EMQX Dashboard and Management API

feat(helm): add dashboard and mgmt api ingress

---

.ci/build_packages/Dockerfile
Makefile

fix the issue of compile failure when LC_ALL is not equal to en_US.UTF-8
close #604

fix(build): fix compile error 

---

deploy/charts/emqx/README.md
deploy/charts/emqx/templates/StatefulSet.yaml
deploy/charts/emqx/values.yaml

Done https://github.com/emqx/emqx-rel/issues/620

feat(helm): support image pull secret

---

deploy/docker/docker-entrypoint.sh

remove useless environmental variables
update the key of the environment variable
fix issue emqx/emqx#4011

fix(docker): fix docker entryponit script

---

rebar.config.script

https://github.com/emqx/emqx-elixir-plugin/issues/15

fix(rebar.config.script): compile rebar_mix after rebar3_run

---

deploy/charts/emqx/templates/StatefulSet.yaml
deploy/charts/emqx/values.yaml

- allow user to change the fsGroup
- put pullSecrets to the correct spot
- allow usage of securityContext for pods

fix(charts): allow custom securityContext + pullSecret
