emqx/emqx-rel

- relx.config
emq_coap.conf requres {{ platform_etc_dir }}.
> Add emq_coap.conf in relx.config.

- Makefile
Tried to build with otp 20, failed.
Then I figured that we probably have stopped supporting it.
This PR adds an assertion as `all` target's dependency to fail fast for otp earlier than 21.
> Fail fast in case the otp version in use is 20 or older

- bin/emqx
emqx release should always use packed erts, not the system provided
> Delete find_erts_dir function

- bin/emqx
- bin/nodetool
There is a race condition when setting node name right after epmd is started.
This PR is to change the nodetool behaviour so it would not set node name (and cookie)
for config management.
> Avoid setting nodename and cookie for config management

- data/loaded_plugins
Enabling delayed_publish cases some overhead when publishing messages. 
We enabled this plugin before for MQTT delayed will message. But after emqx/emqx#1889, we use session proc instead to handle the delayed will msg. We can now disable this plugin by default.
> Don't start delay_publish plugin by default

- vars-pkg.config
Stop guessing /usr/lib64 to overly complicate it
> Always assume emqx is installed to /usr/lib/emqx

- Makefile
- erlang.mk
Also made git clone backward compatible for git older than 1.8
because -b option can not be used with git tag in git 1.7
> Rename VSN in Makefile to a less-clashing name

- Makefile
- erlang.mk
To make it backward compatible because --first-parent option
is not available in git 1.8 etc.
Also deleted --dirty option so to allow auto patching
deps without always having a 'dirty' vsn in e.g. emqx.app
> Fix git describe in erlang.mk

- bin/emqx_ctl
To support args that contains white spaces and/or specail characters that reserved by shell, the args need to be quoted when passing them between shell scripts.
For example:
```shell
./bin/emqx_ctl rules create 'inspect' 'message.publish' 'select * from t1' 'default:debug_action' '{}' 'Rule for debug'
```
> Fix cli args passing issue

- .gitignore
- Makefile
- data/loaded_plugins
- data/loaded_plugins.tmpl
- post-compile.sh
- rebar.config
- rebar.config.script
- vars-cloud.config
- vars-edge.config
This is the very first step deprecating erlang.mk
Not changing dependency versioning and locking issues in this PR,
not that it's not important, but simply because it is a whole different issue
which can be and should be addressed separately.
Marked as WIP because some dependencies have PR to merge.
profiles:
* cloud_dev
* cloud_rel
* edge_dev
* edge_rel
`rebar3 as cloud_dev release` to make a cloud dev release.
> [WIP] [TAKE-2] Make possible to build release with rebar3

- Makefile
Prior to this change, emqx_rel will support get all dependencies from
deps git repo and cannot automatically choose the tag it would release.
This change make emqx build more intelligent.
> Enhance makefile

- bin/emqx_ctl
Provide a clue on why ctl can't be executed. For instance:
```
/opt/emqx/bin/emqx_ctl: line 51: echoerr: not found
['2020-02-18T21:14:24Z']:emqx not running, waiting for recovery in 0 seconds
```
```
vm.args needs to have a -setcookie parameter.
['2020-02-18T21:14:24Z']:emqx not running, waiting for recovery in 0 seconds
```
Example doesn't say much why it cookie can't be found, howerver it pointed to a culprit: [egreg](https://github.com/emqx/emqx-rel/blob/ac33d284fcefbe7b8d703206c21b2e0e3a0cb5d7/bin/emqx_ctl#L38), which failed to parse out cookies from the config file (due to locked file on the file-system by docker):
```
egrep '^[ \t]*node.cookie[ \t]*=[ \t]*' /opt/emqx/etc/emqx.conf
egrep: /opt/emqx/etc/emqx.conf: I/O error
```
Would be much better if `emqx_ctl` could report errors …
> add missing definition of echoerr function

- deploy/docker/Dockerfile
- deploy/docker/start.sh
+ Use the API instead of emqx_ctl to get the broker's status
+ Output to the container using erlang.log instead of emqx.log
+ Fix https://github.com/emqx/emqx/issues/3274
> Use the API instead of emqx_ctl to get the broker's status

- deploy/charts/emqx/templates/service.yaml
I saw `service.annotations` values in the README, but it seems to be missing from the service template. This PR adds the missing part to the service template.
> Add helm chart service annotations

- bin/emqx
- deploy/docker/start.sh
+ Fix an error where the container could not print a new log when the log content was too large
+ When the user sets the environment variables of `RUN_ERL_LOG_GENERATIONS` and `RUN_ERL_LOG_MAXSIZE`, the value set by the user is used
+ Done https://github.com/emqx/emqx/issues/3559
> fix(docker): Fix the error that the container log does not print

- bin/emqx
- bin/install_upgrade.escript
The upgrade commands with arguments not working:
```
emqx upgrade --no-permanent 4.2.1
```
> fix(relup): move unpacking zipballs to install_upgrade.escript

- deploy/packages/rpm/emqx.spec
This is to support hot patches to be installed by `emqx` user to `/usr/lib/emqx/releases`
> chore(rpm): change owner on /usr/lib/emqx in rpm packages

- bin/emqx
fixes #600
set BOOTSTRAP_DEBUG environment variable to enable 'set -x' for
non-sensitive commands
> feat(emqx): Add bootstrap debug option

- rebar.config
Omit the options and source tuples in the list returned by
Module:module_info(compile), and reduce the paths in stack traces to the
module name alone. This option will make it easier to achieve
reproducible builds.
Above is from OTP documentation https://erlang.org/doc/man/compile.html
Another reason is that the absolute path `/path/to/build/dirr/_checkout` prefix
in stacktraces are useless (no app version number in path anyway)
> feat(build): Add deterministic compile option

- deploy/docker/README.md
- deploy/docker/docker-entrypoint.sh
This allows for more config parameters to be added during the container startup.
My usecase for this was a more granular topic retention setup.
By default there is only 3 hooks configured in the emqx_backend_redis.conf for `backend.redis.hook.message.publish.<1-3>` allowing only 1 pattern for message persistance:
```
EMQX_BACKEND__REDIS__HOOK__MESSAGE__PUBLISH__1 = {"topic": "#", "action": {"function": "on_message_publish"}, "pool": "pool1"}
EMQX_BACKEND__REDIS__HOOK__MESSAGE__PUBLISH__2 = {"topic": "#", "action": {"function": "on_message_retain"}, "pool": "pool1"}
EMQX_BACKEND__REDIS__HOOK__MESSAGE__PUBLISH__3 = {"topic": "#", "action": {"function": "on_retain_delete"}, "pool": "pool1"}
```
Any other `EMQX_BACKEND__REDIS__HOOK__MESSAGE__PUBLISH__X` variable will be ignored as it is not …
> Allow extra numbered config parameters to be added from ENV

- deploy/charts/emqx/README.md
- deploy/charts/emqx/templates/StatefulSet.yaml
- deploy/charts/emqx/values.yaml
When EMQX has to work together with other services on kubernetes (like MySQL for `emqx-auth-mysql` plugin), you can take advantage of `initContainers` to wait for other resources to be created.
> support initContainers

- deploy/docker/README.md
- deploy/docker/docker-entrypoint.sh
The sed command substitution of bbmustache style template is stale
emqx no longer releases an unrendered config template
> chore(docker): Delete stale code

- deploy/docker/Dockerfile
- deploy/docker/README.md
- deploy/docker/docker-entrypoint.sh
> Refact docker-entrypoint.sh.
